#!/bin/bash
set -e
cd "$(dirname "$0")"

declare -A URLS=(
  [home]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2RiNDMxNWRjNTcwZjRhMjY5NGUzNzQ0Njc5MGM4NGNmEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [about-us]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2NjZjNhZjI4OTIxNzRjZDg5NzAxY2Y0YjY1ZWFmODJlEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [our-services]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2M5YjNmN2Y2ZDI3ODRlMWQ4MGMyNjM5YTM1MDdkODZiEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [industries]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzMzNDVmMGJhZmQ2MzQyZmE5NGMwYWY5NmEzZGUzMjRmEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [sap]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzU2MjUwMGIzNGRiYTRlYTNhZWYwMjRlZThjZTlkM2U2EgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [oracle]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzFhNjg3MjcwZGJkNTQ2YWQ5MGQ0MDJmMWIyMGQ5M2U0EgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [aerospace]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzM4ZjYxMGRmNDlmNDQ0MTg5ZGU3YWM0ZWU1OWZiMTZjEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [service-sector]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzU5MmJlOWNmM2ZiZDQ0MjlhYzkwMjZlMjM5MDZjNzcwEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [transportation]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzU5MmJlOWNmM2ZiZDQ0MjlhYzkwMjZlMjM5MDZjNzcwEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [pharmaceutical]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzk3NzM1NWM3Yjk5MjQ2ZDVhNDNiNWI3M2VkMjQ0NjAzEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [testimonials]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzcxNDVkMTZkNGFhNjQ1NWE5ODA5ZTI2ZWViYzU3MmZjEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [careers]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzFiOWExODBiZTMxMDQxYjVhNDg2NjYyMmY4NWU5ZjU0EgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [faqs]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzEzY2JiM2ZhM2YwODQxN2Q4ZTM5ZTJjZjJjODQyZDIxEgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
  [contact]="https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzhmZTdmZGQzMTFiNDRiNmFiZGZmNjFlOWFkNjQ4MzY1EgsSBxCy4t7urxMYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAzNjc2MDY5ODgxMjU5NTkyNg&filename=&opi=89354086"
)

for name in "${!URLS[@]}"; do
  curl -sSL -o "${name}.html" "${URLS[$name]}" &
done
wait
ls -la *.html | awk '{print $5, $NF}'
